### ISSUE TITLE
cdc-debezium-source-kafka crashes at incoming delete event

### ISSUE THREAD

**Issue by JohannesM24** [spring-cloud-stream-app-starters/cdc-debezium#6]
When deleting a row the source crashes.

Steps to reproduce (what i did):
1. Build the cdc-debezium-source-kafka-jar according to the readme (tested on newest commit and the 1.0.0.M1 milestone)
2. Create docker conatiner according to the readme for mySQL
3. Additionally grant rights to another master user from where I can insert and delete
4. Start the jar with the configs from readme
5. Insert row into inventory.customers : (1005, 'Johannes', 'M', 'Johannes@M.de')
 
This works fine, i get a log 
`2019-11-21 13:16:22.615  INFO 13271 --- [pool-1-thread-1] i.debezium.connector.mysql.BinlogReader  : 1 records sent during previous 00:00:09,37, last recorded offset: {ts_sec=1574338582, file=mysql-bin.000003, pos=824, row=1, server_id=223344, event=2}
`
and the message appears in the output topic.

`{"schema":{"type":"struct","fields":[{"type":"int32","optional":false,"field":"id"},{"type":"string","optional":false,"field":"first_name"},{"type":"string","optional":false,"field":"last_name"},{"type":"string","optional":false,"field":"email"}],"optional":true,"name":"my_app_connector.inventory.customers.Value"},"payload":{"id":1005,"first_name":"Johannes","last_name":"M","email":"Johannes@M.de"}}
`

6. Delete the previously inserted row, source crashes

```
2019-11-18 14:02:51.393 ERROR 5848 --- [pool-1-thread-1] o.s.c.s.a.c.common.core.EmbeddedEngine   : Stopping connector after error in the application's handler method: null

java.lang.NullPointerException: null
    at org.springframework.cloud.stream.app.cdc.common.core.CdcCommonConfiguration.lambda$valueSerializer$1(CdcCommonConfiguration.java:81) ~[spring-cloud-starter-stream-common-cdc-debezium-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.stream.app.cdc.common.core.CdcStreamConfiguration.lambda$engine$0(CdcStreamConfiguration.java:59) ~[spring-cloud-starter-stream-common-cdc-debezium-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.stream.app.cdc.common.core.CdcStreamConfiguration.lambda$engine$1(CdcStreamConfiguration.java:83) ~[spring-cloud-starter-stream-common-cdc-debezium-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.stream.app.cdc.common.core.EmbeddedEngine$1.handleBatch(EmbeddedEngine.java:402) ~[spring-cloud-starter-stream-common-cdc-debezium-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.stream.app.cdc.common.core.EmbeddedEngine.run(EmbeddedEngine.java:839) ~[spring-cloud-starter-stream-common-cdc-debezium-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
    at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
```

but still writes this message on the output topic

`{"schema":{"type":"struct","fields":[{"type":"int32","optional":false,"field":"id"},{"type":"string","optional":false,"field":"first_name"},{"type":"string","optional":false,"field":"last_name"},{"type":"string","optional":false,"field":"email"}],"optional":true,"name":"my_app_connector.inventory.customers.Value"},"payload":null}
`

Maybe this is just some kind of misunderstanding of me of how to use the source-app and how to handle deletes/tombstones. I eventually want to deploy this on dataflow and build a custom application using the generated topic of events.

**Comment by tzolov** [comment]
@JohannesM24 , thanks for reporting this issue! It is indeed a but in handling delete events when the `dropTombstone` is `true` (e.g. the default value).  This problem is likely to affect all deletion events for DB sources. 

I'm working on a patch hopefully the PR will submitted later today. In the meat time you can use the `--cdc.flattering.dropTombstones=false` configuration which in case of delete generates additional `Tombstones` event.
